EndPoint/Areas/Admin/Controllers/CatalogItem/CatalogItemController.cs
using Application.Catalogs.CatalogBrand;
using Application.Catalogs.CatalogTypes.CrudService;
using Application.Catalogs.CatalohItems.AddNewCatalogItem;
using Application.Catalogs.CatalohItems.CatalogItemServices;
using Application.DTOGeneral;
using AutoMapper;
using EndPoint.ViewModels.Catalogs;
using Infrastructure.ExternalApi.ImageServer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace EndPoint.Areas.Admin.Controllers.CatalogItem
{
    [Area("Admin")]
    public class CatalogItemController : Controller
    {

        private readonly IAddNewCatalogItemService addNewCatalogItemService;
        private readonly ICatalogItemService catalogItemService;
        private readonly IImageUploadService    imageUploadService;
        private readonly IMapper mapper;
       
        public CatalogItemController(IAddNewCatalogItemService _addNewCatalogItemService
            ,ICatalogItemService _catalogItemService
            , IImageUploadService _imageUploadService
            , IMapper _mapper)
        {
            catalogItemService = _catalogItemService;
            mapper = _mapper;
            addNewCatalogItemService=_addNewCatalogItemService;
            imageUploadService = _imageUploadService;
        }



        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public IActionResult Create()
        {

            AddNewCatalogItemViewModel catalogItem = new AddNewCatalogItemViewModel();

       
            List<ListCatalogTypeDto> Types=catalogItemService.GetCatalogType();
            List<CatalogBrandDto> Brands = catalogItemService.GetBrand();



            
            catalogItem.CatalogTypeList = Types.Select(p=>new SelectListItem { Text=p.Type,Value=p.Id.ToString()}).ToList();
            catalogItem.CatalogBrandList = Brands.Select(p => new SelectListItem { Text = p.Brand, Value = p.Id.ToString() }).ToList();

       

            return View(catalogItem);
         
        }

        public List<IFormFile> ListFiles { get; set; }
        public AddNewCatalogItemDto _addNewCatalogItemDto { get; set; }

        [HttpPost]
        public IActionResult Create(AddNewCatalogItemDto frombody)
        {
            if (!ModelState.IsValid)
            {
                var allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return new JsonResult(new BaseDto<int>(0, false, allErrors.Select(p => p.ErrorMessage).ToList()));
            }
            for (int i = 0; i < Request.Form.Files.Count; i++)
            {
                var file = Request.Form.Files[i];
                ListFiles.Add(file);
            }
            //ابتدا آپلود می کنیم
            //وقتی آپلود می کنیم آدرس بر می گردونه
            //_addNewCatalogItemDto لیست آدرس  عکس ها را  هم دارد
            //خروجی آپلود ، لیست آدرس می باشد

            List<AddNewCatalogItemImage_Dto> ListImages = new List<AddNewCatalogItemImage_Dto>();
            if (ListFiles.Count > 0)
            {
                //Upload 
                //بعد از آپلود لیست آدرس را بر می گردونه
              var result=imageUploadService.Upload(ListFiles);
                foreach (var item in result)
                {
                    //آن آدرس ها را می گیریم و به ازای هر  کاتالوگ ذخیره می کنیم
                    ListImages.Add(new AddNewCatalogItemImage_Dto { Src = item });
                }
            }


            _addNewCatalogItemDto.ListSrcImages = ListImages;
            var resultService = addNewCatalogItemService.Execute(_addNewCatalogItemDto);
            return new JsonResult(resultService);


        }
    }
}

EndPoint/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EndPoint</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EndPoint.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EndPoint</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="CategoryType" asp-action="Index">CatalogType</a>

                           
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="CatalogItem" asp-action="create">CatalogItem</a>

                           
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <nav>
            <ul>
                <li>
                    <a href=""> همه ی دسته بندی های </a>
                    <menu-item></menu-item>
                </li>
            </ul>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EndPoint - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>